name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Build the image
        if: ${{ success() }}
        run: |
          docker-compose build
          docker image ls
      - name: Tag the image
        if: ${{ success() }}
        run: docker tag t-nsa-800_app nexus.gabrielhamel.fr/repository/app-docker/web-php:1.0
      - name: Login to Nexus Docker registry
        if: ${{ success() }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          registry: nexus.gabrielhamel.fr
      - name: Tag and push the image
        if: ${{ success() }}
        run: docker push nexus.gabrielhamel.fr/repository/app-docker/web-php:1.0