name: deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start the image with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.APP_WEB_HOST }}
          username: ${{ vars.APP_WEB_USERNAME }}
          passphrase: ${{ secrets.APP_WEB_PASSWORD }}
          key: ${{ secrets.SSH_KEY_APP_WEB }}
          port: ${{ vars.APP_WEB_PORT }}

          # login then stop the container then start our container
          script: |
            sudo docker login https://nexus.gabrielhamel.fr/ -u ${{ vars.NEXUS_USERNAME }} -p "${{ secrets.NEXUS_PASSWORD }}"
            sudo docker stop app-web || true
            sudo docker rm app-web || true
            sudo docker run -d --name app-web -v web-app-vol nexus.gabrielhamel.fr/repository/app-docker/web-php:1.0
