name: deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start the image with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.APP_WEB_HOST }}
          username: ${{ secrets.APP_WEB_USERNAME }}
          password: ${{ secrets.APP_WEB_PASSWORD }}
          key: ${{ secrets.SSH_KEY_APP_WEB }}
          port: ${{ secrets.APP_WEB_PORT }}
          script: docker start ${{ secrets.REGISTRY_URL }}
