name: scan

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: docker build -t docker.io/epitech/sample-app:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/epitech/sample-app:${{ github.sha }}'
          format: 'sarif'
          output: 'scan.sarif'
      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'scan.sarif'